export const actionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  CLEAR_CART: "CLEAR_CART",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  TOGGLE_MODAL: "TOGGLE_MODAL",
};
